import { Inter, Barlow } from 'next/font/google';
import { notFound } from 'next/navigation';

import { Ii18nLocales, IRootLayoutProps } from '@/types/global';
import { AppProvider } from '@/config/AppProvider';

import { getI18nLocales } from '@/utils/getI18nLocales';

import './globals.css';

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-barlow',
});

export function generateStaticParams(): Ii18nLocales[] {
  return getI18nLocales();
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children,
  params: { locale }
}: IRootLayoutProps): Promise<JSX.Element> {
  let localesFile;

  try {
    localesFile = (await import(`../../locales/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={barlow.className}>
        <AppProvider locale={locale} messages={localesFile}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
